name = "jl"
defaultTargets = ["JL.JL"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "JL"
autoImportImports = true

[[lean_exe]]
name = "jl-tests"
main = "JLTest.lean"
